Repository razorpay/hermes, pull requests merged in 2023-07, with the labels that each got.

#6 PR #1 : Github Actions, Docker, Environmental Variables
  .github/workflows/ci.yml
  .gitignore
  .yarn/releases/yarn-3.3.0.cjs
  .yarnrc.yml
  Dockerfile.indexer
  Dockerfile.server
  README.md
  config.hcl
  docker-compose.yml
  go.mod
  go.sum
  internal/cmd/commands/indexer/indexer.go
  internal/cmd/commands/server/server.go
  internal/db/db.go
  internal/indexer/indexer.go
  package.json
  pkg/googleworkspace/service.go
Labels: enhancement

#9 PR #4: Backend of subfolder, dynamic creation of teams/products, algolia dependency removed completely, frontend enhanced
  .idea/.gitignore
  .idea/hermes.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  internal/api/products.go
  internal/api/teams.go
  internal/cmd/commands/server/server.go
  internal/structs/teams.go
  pkg/models/gorm.go
  pkg/models/product.go
  pkg/models/team.go
  pkg/models/user.go
  web/app/components/header/index.hbs
  web/app/components/inputs/product-select/index.ts
  web/app/components/inputs/team-select/index.hbs
  web/app/components/inputs/team-select/index.ts
  web/app/components/new/doc-form.hbs
  web/app/components/new/doc-form.ts
  web/app/controllers/authenticated/dashboard.js
  web/app/routes/authenticated/dashboard.js
  web/app/styles/app.scss
  web/app/templates/authenticated/dashboard.hbs
  web/ember-cli-build.js
  web/mirage/config.ts
  web/package.json
  web/tests/unit/controllers/authenticated/create-bu-test-test.js
  web/tests/unit/controllers/authenticated/create-bu-test.js
  web/yarn.lock
Labels: ReadyForReview, enhancement

#10 PR #5: Final Working all feature uptil "send doc for review" including BU and Team
  .github/workflows/ci.yml
  internal/api/drafts.go
  internal/api/reviews.go
  internal/db/db.go
  internal/email/email.go
  internal/email/templates/contributor.html
  internal/email/templates/review-requested.html
  pkg/hashicorpdocs/basedoc.go
  pkg/hashicorpdocs/common.go
  pkg/models/document.go
  pkg/models/product.go
  pkg/models/product_latest_document_number.go
  pkg/models/team.go
  web/app/components/document/sidebar.hbs
  web/app/components/document/sidebar.ts
  web/app/components/inputs/product-select/index.hbs
  web/app/components/inputs/product-select/item.hbs
  web/app/components/inputs/team-select/index.hbs
  web/app/components/inputs/team-select/item.hbs
  web/app/components/new/doc-form.ts
  web/app/templates/authenticated/dashboard.hbs
  web/app/types/document.d.ts
  web/mirage/config.ts
Labels: enhancement

#16 PR #8: Minor Bug resolved, application Revived
  .github/workflows/ci.yml
  web/app/components/inputs/product-select/index.ts
  web/app/components/new/doc-form.ts
Labels: Minor Fix

#11 Template management - Template Creation Front End
  web/app/components/new/template-form.hbs
  web/app/components/new/template-form.ts
  web/app/config/environment.d.ts
  web/app/router.js
  web/app/routes/authenticated/new/doc.js
  web/app/services/config.ts
  web/app/templates/authenticated/new/custom-template.hbs
  web/app/templates/authenticated/new/index.hbs
  web/config/environment.js
Labels: enhancement

#15 PR #7: Commented part Removal
  internal/api/products.go
  internal/api/teams.go
  pkg/models/product.go
  pkg/models/team.go
Labels: Minor Fix

#17 PR #8: User Roles created: Enum added, Profile Page Created,
  internal/api/me.go
  internal/cmd/commands/server/server.go
  pkg/models/user.go
  web/app/components/header/nav.hbs
  web/app/controllers/authenticated/dashboard.js
  web/app/controllers/authenticated/myprofile.js
  web/app/controllers/authenticated/myprofile.ts
  web/app/router.js
  web/app/routes/authenticated/myprofile.js
  web/app/services/authenticated-user.ts
  web/app/styles/app.scss
  web/app/templates/authenticated/dashboard.hbs
  web/app/templates/authenticated/myprofile.hbs
  web/tests/integration/components/header/nav-test.ts
  web/tests/unit/controllers/authenticated/myprofile-test.js
  web/tests/unit/routes/authenticated/myprofile-test.js
Labels: enhancement

#18 PR #10: Integrated Slack-Bot with the the application
  go.mod
  go.sum
  internal/api/drafts.go
  internal/api/reviews.go
  internal/slack-bot/getUser.go
  internal/slack-bot/message_template.go
  internal/slack-bot/slack-bot.go
Labels: enhancement

#21 changed all static doc preview to dynamic +UI upgrade+ minor bug fix
  internal/api/custom_templates.go
  internal/pkg/doctypes/doc_types.go
  web/app/components/doc/row.hbs
  web/app/components/doc/thumbnail.hbs
  web/app/components/doc/thumbnail.ts
  web/app/components/doc/tile.hbs
  web/app/components/doc/tile.ts
  web/app/components/new/doc-form.ts
  web/app/components/new/template-form.hbs
  web/app/components/new/template-form.ts
  web/app/styles/components/preview-card.scss
Labels: enhancement, Minor Fix

#23 PR #12: Admin Controls
  internal/cmd/commands/server/server.go
  pkg/models/user.go
  web/app/controllers/authenticated/dashboard.js
  web/app/templates/authenticated/dashboard.hbs
  web/app/templates/authenticated/myprofile.hbs
Labels: enhancement

#24 PR #13 Make someone Admin
  internal/api/make_admin.go
  internal/cmd/commands/server/server.go
Labels: enhancement

#26 Delete & Edit Template
  internal/api/custom_templates.go
  internal/cmd/commands/server/server.go
  web/app/components/delete-template.hbs
  web/app/components/delete-template.ts
  web/app/components/edit-template.hbs
  web/app/components/edit-template.ts
  web/app/styles/components/template-card.scss
  web/app/templates/authenticated/new/index.hbs
  web/app/types/document.d.ts
  web/public/images/create.png
Labels: ReadyForReview, enhancement, Minor Fix

#27 PR #14: Make someone Admin, View Directory and minor UI refinements....
  web/app/components/collapsible-folder.hbs
  web/app/components/collapsible-folder.js
  web/app/components/footer.hbs
  web/app/components/header/nav.hbs
  web/app/components/header/nav.ts
  web/app/components/hermes-logo.hbs
  web/app/controllers/authenticated/dashboard.js
  web/app/styles/app.scss
  web/app/templates/authenticate.hbs
  web/app/templates/authenticated/dashboard.hbs
  web/ember-cli-build.js
  web/package.json
  web/public/images/logo.png
  web/tests/integration/components/collapsible-folder-test.js
  web/yarn.lock
Labels: enhancement

#29 PR #15 : Various small big updates
  internal/api/drafts.go
  internal/api/products.go
  internal/api/reviews.go
  internal/api/teams.go
  internal/cmd/commands/server/server.go
  internal/email/email.go
  internal/email/templates/contributor.html
  internal/email/templates/review-requested.html
  internal/slack-bot/message_template.go
  internal/slack-bot/slack-bot.go
  pkg/models/document.go
  pkg/models/document_review_test.go
  pkg/models/document_test.go
  pkg/models/product.go
  pkg/models/product_latest_document_number_test.go
  pkg/models/product_test.go
  pkg/models/team.go
  pkg/models/user_test.go
  web/app/components/doc/tile.hbs
  web/app/components/document/sidebar.hbs
  web/app/controllers/authenticated/dashboard.js
  web/app/templates/authenticated/dashboard.hbs
  web/app/templates/authenticated/myprofile.hbs
Labels: enhancement

#30 Review workflow bug fix
  internal/api/documents.go
  web/app/components/document/sidebar.ts
Labels: bug

#31 CTA on Top Nav Bar
  web/app/components/header/nav.hbs
  web/app/styles/components/nav.scss
Labels: enhancement

#38 PR #17: Enhancement of Documents.go
  internal/api/documents.go
  pkg/hashicorpdocs/common.go
  pkg/models/document.go
Labels: bug, enhancement

#42 PR #18: Directory added and Minor Fixes
  internal/email/templates/subscriber-document-published.html
  internal/slack-bot/getUser.go
  internal/slack-bot/message_template.go
  internal/slack-bot/slack-bot.go
  pkg/algolia/client.go
  web/app/components/collapsible-folder.hbs
  web/app/components/collapsible-folder.js
  web/app/components/header/nav.hbs
  web/app/components/header/nav.ts
  web/app/components/hermes-logo.hbs
  web/app/components/inputs/product-select/index.hbs
  web/app/components/inputs/project-select/index.hbs
  web/app/components/inputs/team-select/index.hbs
  web/app/components/new/doc-form.hbs
  web/app/components/new/doc-form.ts
  web/app/controllers/authenticated/dashboard.js
  web/app/index.html
  web/app/router.js
  web/app/routes/authenticated/business-units.js
  web/app/routes/authenticated/files.js
  web/app/routes/authenticated/project.js
  web/app/routes/authenticated/projects.js
  web/app/routes/authenticated/teams.js
  web/app/styles/app.scss
  web/app/styles/components/doc/directory.scss
  web/app/styles/components/doc/tile-list.scss
  web/app/templates/application.hbs
  web/app/templates/authenticated/business-units.hbs
  web/app/templates/authenticated/dashboard.hbs
  web/app/templates/authenticated/files.hbs
  web/app/templates/authenticated/project.hbs
  web/app/templates/authenticated/projects.hbs
  web/app/templates/authenticated/teams.hbs
  web/public/images/favicon.png
  web/public/images/logo.png
  web/tests/integration/components/folder-view-test.js
  web/tests/unit/routes/authenticated/business-units-test.js
  web/tests/unit/routes/authenticated/files-test.js
  web/tests/unit/routes/authenticated/project-test.js
  web/tests/unit/routes/authenticated/projects-test.js
  web/tests/unit/routes/authenticated/teams-test.js
Labels: bug, enhancement
